variables:
  CIBW_BUILD: cp38-*
  CIBW_BEFORE_BUILD_LINUX: "yum -y install fftw-devel; git clean -xfd -e wheelhouse"
  CIBW_BEFORE_BUILD_MACOS: "brew install fftw; git clean -xfd -e wheelhouse"

jobs:

- template: publish.yml
  parameters:
    artifact_project: azure-pipelines-templates
    artifact_feed: testfeed
    remove_local_scheme: true
    libraries:
      - libfftw3-dev
    targets:
      - wheels_linux
      - wheels_macos
      - wheels_cp3[78]-win_amd64
      - wheels_cp37-manylinux_x86_64
      - wheels_cp37-manylinux_aarch64
      - sdist

# - template: publish.yml
#   parameters:
#     libraries:
#       - libfftw3-dev
#     targets:
#       - wheels_universal
